name: Run Tests

on:
  push:   # runs on every push
    branches: 
      - main   # change if your default branch is different
  pull_request: # also run on pull requests
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # use your project Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false
